package com.example.rpg.Calc.map.world_map;

import java.io.Serializable;
import static com.example.rpg.Calc.map.PersonHome1.*;

import com.example.rpg.Calc.map.Map;
import com.example.rpg.Calc.map.tail.EntranceAndExitTail;
import com.example.rpg.Calc.map.tail.ErrorTail;
import com.example.rpg.Calc.map.tail.GlassTail;
import com.example.rpg.Calc.map.tail.GravelTail;
import com.example.rpg.Calc.map.tail.OceanTail;
import com.example.rpg.Calc.map.tail.StoneTail;
import com.example.rpg.Calc.map.tail.Tail;
import com.example.rpg.Calc.map.tail.WoodTail;
import com.example.rpg.graphic.TransitionActivity;

public class World_map extends Map implements Serializable {
    public static Tail[][] world_map = {
            {new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new OceanTail(0,0,false), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GravelTail(0,1), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new EntranceAndExitTail(1,"to_people_home1",0), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new OceanTail(0,0,false), new OceanTail(0,0,true), new OceanTail(0,0,false), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GravelTail(0,1), new GravelTail(1,1), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2), new GlassTail(0,2),new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new OceanTail(0,0,false), new OceanTail(0,0,true), new OceanTail(0,0,true), new OceanTail(0,0,true), new OceanTail(0,0,false), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(1,0), new GravelTail(0,1), new GravelTail(1,1), new GravelTail(1,1), new GravelTail(1,1), new GravelTail(1,1), new GravelTail(1,1), new GravelTail(1,1), new GravelTail(1,1), new GravelTail(1,1), new GravelTail(1,1), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new OceanTail(0,0,false), new OceanTail(0,0,true), new OceanTail(0,0,true), new OceanTail(0,0,true), new OceanTail(0,0,false), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(1,0), new GlassTail(1,0), new GravelTail(0,1), new GravelTail(0,1), new GravelTail(0,1), new GravelTail(0,1), new GlassTail(1,0), new GlassTail(1,0), new GlassTail(1,0), new GravelTail(0,1), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new OceanTail(0,0,false), new OceanTail(0,0,true), new OceanTail(0,0,false), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(1,0), new GlassTail(1,0), new GlassTail(1,0), new GlassTail(1,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(1,0), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new OceanTail(0,0,false), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new EntranceAndExitTail(0,"to_cave1",0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new EntranceAndExitTail(2,"to_store1",0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new ErrorTail()},
            {new ErrorTail(), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new GlassTail(0,0), new ErrorTail()},
            {new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail(), new ErrorTail()}
    };
}
